### PR TITLE
Remove libc dependencies in enclave initialisation + add instrumentation

### LINKED ISSUE #564: [Tests] Rare segfault immediately after enclave_init
The following has happened in CI for kernel-syscalls-times-times01-(nonrelease)-(run-sw)-(8-ethreads):
```
[   SGX-LKL  ] SGX-LKL (OE) 0.2.0-dev (3694a68) LKL 5.3.0 [NON-RELEASE build (-O3)] [SOFTWARE DEBUG]
[   SGX-LKL  ] Warning: SGXLKL_TRACE_SIGNAL ignored in non-debug mode.
[   SGX-LKL  ] nproc=8 ETHREADS=8 CMDLINE="mem=512m"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=0
[   SGX-LKL  ] Registering disk 0 (path='sgxlkl-miniroot-fs.img', mnt='/', [RW    ])
[   SGX-LKL  ] No tap device specified, networking will not be available.
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-nonrelease/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... result=0 (OE_OK)
[   SGX-LKL  ] sgxlkl_enclave_init(ethread_id=0)
[[  SGX-LKL ]] WARN: Unhandled exception SIGSEGV (page fault) received (code=5 addr=0x160 opcode=0x8948 lkl_is_running()=0 ret=0)
[[  SGX-LKL ]] WARN: Unhandled exception SIGSEGV (page fault) received (code=5 addr=0x160 opcode=0x8948 lkl_is_running()=0 ret=0)
```

The above problem may also explain other issues immediately after enclave initialisation. I have not observed this for the DEBUG build (yet?).

### PR DESCRIPTION
**Pull request by prp**
This PR attempts to fix #564. It removes references to libc functions (`snprintf`, `memset`, ...) early in the enclave initialisation sequence, before libc has been initialised. Without libc `malloc` being initialised, such calls may fail. The PR also removes a dependency on shared/env.c. 

The PR doesn't appear to fully solve the problem reported in #564, which now happens rather rarely in CI pipeline runs. Therefore, this PR also adds more instrumentation that should help debug #564 from CI logs.

### CODE REVIEW

File: src/enclave/enclave_oe.c [hunk 1]
```diff
@@ -24,30 +20,56 @@ int __sgx_init_enclave()
     return __libc_init_enclave(sgxlkl_enclave->argc, sgxlkl_enclave->argv);
 }
 
-void sgxlkl_enclave_show_attribute(const void* sgxlkl_enclave_base)
+#ifdef DEBUG
+static void _size_uint64_to_str(uint64_t size, char* buf, uint64_t len)
+{
+    int i = 0;
+    double bytes = size;
+    const char* units[] = {"B", "KB", "MB", "GB", "TB", "PB"};
```
Comment (davidchisnall) [inline src/enclave/enclave_oe.c]:
```suggestion
    const char* units[] = {"B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB"};
```
2^64 B is 16 EiB, so we need EiB to support all possible values in callers of this.

**Review by davidchisnall — APPROVED** [review]

File: src/enclave/enclave_oe.c (hunk 1 above)
Comment (prp) [reply src/enclave/enclave_oe.c]: Done.

**Comment by prp** [comment]
Hmm, there still seems to be (another?) bug causing segfaults here: https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=1082&view=ms.vss-test-web.build-test-results-tab&runId=17572&resultId=100041&paneView=attachments

I've added more verbose output to reproduce this in the CI pipeline.

**Comment by davidchisnall** [comment]
Looks as if the extra tracing fixed the segfaults?

**Comment by prp** [comment]
> Looks as if the extra tracing fixed the segfaults?

I only saw the segfault after running the CI pipeline several times, so I'll keep triggering it and see what I get. The new tracing will help pinpoint where in the initialisation sequence it segfaults.

**Comment by prp** [comment]
Gotcha:
```
[   SGX-LKL  ] SGX-LKL (OE) 0.2.0-dev (3722355) LKL 5.3.0 [DEBUG build (-O0)] [HARDWARE DEBUG]
[   SGX-LKL  ] nproc=4 ETHREADS=8 CMDLINE="mem=512m"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='sgxlkl-miniroot-fs.img', mnt='/', [RW    ])
[   SGX-LKL  ] No tap device specified, networking will not be available.
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... result=0 (OE_OK)
[   SGX-LKL  ] sgxlkl_enclave_init(ethread_id=0)
[[  SGX-LKL ]] sgxlkl_enclave_init(): enter
[[  SGX-LKL ]] _sgxlkl_enclave_show_attribute(): enclave base=0x7fcc00000000 size=2.0 GiB
[[  SGX-LKL ]] _sgxlkl_enclave_show_attribute(): enclave heap base=0x7fcc00b55000 size=1024.0 MiB end=0x7fcc40b55000
[[  SGX-LKL ]] sgxlkl_enclave_init(): calling _dlstart_c()
[[  SGX-LKL ]] _register_enclave_signal_handlers(): Registering OE exception handler...
[[  SGX-LKL ]] __libc_init_enclave(): enclave_mman_init() finished
[[  SGX-LKL ]] __libc_init_enclave(): init_clock_res() finished
[[  SGX-LKL ]] __libc_init_enclave(): newmpmcq() finished
[[  SGX-LKL ]] __libc_init_enclave(): __init_tls() finished
[[  SGX-LKL ]] __libc_init_enclave(): _lthread_sched_init() finished
[[  SGX-LKL ]] WARN: [[  SGX-LKL ]] lkl_start_init(): kernel command line: 'mem=512m console=hvc0'
[[  SGX-LKL ]] lkl_start_init(): lkl_start_kernel() called
Unhandled exception SIGSEGV (page fault) received (code=5 addr=0x7fcc005c7834 opcode=0x8948 lkl_is_running()=0 ret=0)
[[  SGX-LKL ]] WARN: Unhandled exception SIGSEGV (page fault) received (code=5 addr=0x7fcc005c7834 opcode=0x8948 lkl_is_running()=0 ret=0)
[[  SGX-LKL ]] WARN: Unhandled exception SIGSEGV (page fault) received (code=5 addr=0x7fcc005c7834 opcode=0x8948 lkl_is_running()=0 ret=0)
[[  SGX-LKL ]] WARN: Unhandled exception SIGSEGV (page fault) received (code=5 addr=0x7fcc005c7834 opcode=0x8948 lkl_is_running()=0 ret=0)
```

**Comment by davidchisnall** [comment]
Mem=512m? I wonder if we’re sometimes seeing sufficient fragmentation that we can’t do that allocation? The host malloc function doesn’t check for failure in the enclave mmap, so may end up returning -1, which would lead to some exciting segfaults here.

**Comment by prp** [comment]
> Mem=512m? I wonder if we’re sometimes seeing sufficient fragmentation that we can’t do that allocation? The host malloc function doesn’t check for failure in the enclave mmap, so may end up returning -1, which would lead to some exciting segfaults here.

Hmm, that wouldn't explain this segfault, as it happens before we have called the bootmem initialisation that allocates the LKL  kernel memory.

That said, I agree that we shouldn't be running the LTP tests with a different amount of LKL memory. We should raise a separate PR to change this.

**Comment by prp** [comment]
@wintersteiger could you review this? I would like to merge this PR, as it gives more detailed output when segfaults happen during the CI pipeline run.

**Comment by wintersteiger** [comment]
Sure, no problem.

File: src/enclave/enclave_event_channel.c [hunk 2]
```diff
@@ -145,18 +150,36 @@ void initialize_enclave_event_channel(
...
     evt_chn_lock = (struct ticketlock**)oe_calloc(
         evt_channel_num, sizeof(struct ticketlock*));
+    if (!evt_chn_lock)
+    {
+        sgxlkl_fail("Could not allocate memory for evt_chn_lock\n");
+    }
 
     vio_tasks =
         (struct lthread**)oe_calloc(evt_channel_num, sizeof(struct lthread*));
+    if (!vio_tasks)
```
Comment (davidchisnall) [inline src/enclave/enclave_event_channel.c]: This pattern is repeated a lot.  Is it worth adding a helper along the lines of:
```c
void *oe_alloc_or_die(size_t size, size_t count, const char *fail_msg)
{
  void *ptr = oe_calloc(size, count);
  if (ptr == NULL)
  {
    sgxlkl_fail(fail_msg);
  }
  return ptr;
}
```

Comment (prp) [reply src/enclave/enclave_event_channel.c]: Good idea. Where shall we put this?

File: src/enclave/enclave_event_channel.c [hunk 3]
```diff
@@ -145,18 +150,36 @@ void initialize_enclave_event_channel(
 
     evt_chn_lock = (struct ticketlock**)oe_calloc(
         evt_channel_num, sizeof(struct ticketlock*));
+    if (!evt_chn_lock)
+    {
+        sgxlkl_fail("Could not allocate memory for evt_chn_lock\n");
```
Comment (wintersteiger) [inline src/enclave/enclave_event_channel.c]: I wonder if we should add a checked-malloc macro. At least in src/enclave we always abort anyways and it would make the code more compact.

File: src/enclave/enclave_event_channel.c [hunk 4]
```diff
@@ -145,18 +150,36 @@ void initialize_enclave_event_channel(
...
     for (int i = 0; i < evt_channel_num; i++)
     {
         evt_chn_lock[i] =
             (struct ticketlock*)oe_calloc(1, sizeof(struct ticketlock));
+        if (!evt_chn_lock[i])
+        {
+            sgxlkl_fail("Could not allocate memory for evt_chn_lock[%i]\n", i);
+        }
+
         memset(evt_chn_lock[i], 0, sizeof(struct ticketlock));
```
Comment (wintersteiger) [inline src/enclave/enclave_event_channel.c]: This is already `calloc`'d, I don't think the `memset` is necessary.

File: src/enclave/enclave_event_channel.c (hunk 3 above)
Comment (prp) [reply src/enclave/enclave_event_channel.c]: Yeah, David suggested the same. Where would we put it, as we don't want to edit the OE headers?

File: src/enclave/enclave_init.c [hunk 5]
```diff
@@ -231,16 +227,21 @@ int __libc_init_enclave(int argc, char** argv)
     libc.user_tls_enabled =
         sgxlkl_enclave->mode == SW_DEBUG_MODE ? 1 : sgxlkl_enclave->fsgsbase;
 
+    SGXLKL_VERBOSE("calling init_sysconf()\n");
     init_sysconf(
         sgxlkl_enclave->sysconf_nproc_conf, sgxlkl_enclave->sysconf_nproc_onln);
+
+    SGXLKL_VERBOSE("calling init_clock_res()\n");
```
Comment (wintersteiger) [inline src/enclave/enclave_init.c]: This type of output is super verbose, maybe we want a new flag or a trace for this. Maybe someone could look into extracting stack traces on error?

Comment (prp) [reply src/enclave/enclave_init.c]: I think that the whole tracing needs to be rethought (we have #215 for this), but I don't want to do this as part of this PR. If we catch some of the initialisation segfaults, I can do another PR that removes some of these messages again.

Having stack traces would be wonderful, but getting these to work with symbols would require some work because of the custom way how we load them.

File: src/include/openenclave/internal/utils.h [hunk 6]
```diff
@@ -0,0 +1,233 @@
+// Copyright (c) Open Enclave SDK contributors.
```
Comment (wintersteiger) [inline src/include/openenclave/internal/utils.h]: If we can avoid internal OE headers, we should. I can't easily see why we need it here. If it's just for the round-up to the next power of 2, I think we should re-implement that ourselves.

File: src/sched/lthread.c [hunk 7]
```diff
@@ -1079,3 +1079,23 @@ void lthread_set_expired(struct lthread* lt)
...
 }
+
+#ifdef DEBUG
+void lthread_dump_all_threads(void)
+{
+    struct lthread_queue* lt_queue = __active_lthreads;
+
+    SGXLKL_VERBOSE("Dumping all lthreads:\n");
+
+    for (int i = 1; lt_queue; i++)
```
Comment (wintersteiger) [inline src/sched/lthread.c:1090]: The `1` here is probably correct, but I'm missing the context to say so for sure.

**Review by wintersteiger — APPROVED** [review]
I think this is fine, I left some optional comments.

File: src/enclave/enclave_event_channel.c (hunk 2 above)
Comment (wintersteiger) [reply src/enclave/enclave_event_channel.c]: +1, I just said the same in my review. I was thinking along the lines of `#define CHECKED_CALLOC(X,Y) if ((X = oe_calloc(1, (Y)) == NULL) oe_abort();`

File: src/enclave/enclave_init.c (hunk 5 above)
Comment (wintersteiger) [reply src/enclave/enclave_init.c]: Yeah, you're right, that should be part of the general tracing changes. 

I think for the kernel and below, `oe_print_backtrace()` should work, which may help with some of our CI debugging. But yeah, correctly loading symbols from application code is likely a lot of effort.

File: src/enclave/enclave_event_channel.c (hunk 3 above)
Comment (wintersteiger) [reply src/enclave/enclave_event_channel.c]: Maybe `enclave_util.h`?

File: src/enclave/enclave_init.c (hunk 5 above)
Comment (prp) [reply src/enclave/enclave_init.c]: I tried it a while back, and it didn't work even for libsgxlkl.so symbols.

Comment (wintersteiger) [reply src/enclave/enclave_init.c]: I see! I might have a few spare minutes over the weekend, maybe I'll take another look at it.

File: src/enclave/enclave_event_channel.c (hunk 2 above)
Comment (prp) [reply src/enclave/enclave_event_channel.c]: Done.

File: src/enclave/enclave_event_channel.c (hunk 4 above)
Comment (prp) [reply src/enclave/enclave_event_channel.c]: Done.

File: src/include/openenclave/internal/utils.h (hunk 6 above)
Comment (prp) [reply src/include/openenclave/internal/utils.h]: Done.

File: src/sched/lthread.c (hunk 7 above)
Comment (prp) [reply src/sched/lthread.c:1090]: We use this to prefix the printed lines, and this can start from 1 when counting the threads.

File: src/enclave/enclave_event_channel.c (hunk 3 above)
Comment (prp) [reply src/enclave/enclave_event_channel.c]: Done.
