### PR TITLE
Report unhandled exceptions during LKL shutdown

### LINKED ISSUE #560: [Tests] Failure to shutdown SGX-LKL after lthread_detach2()
There is an random enclave error during the shutdown sequence that makes tests fail:
```
Execution timeout: 60
Will run tests for run-hw
/opt/sgx-lkl-debug/bin/sgx-lkl-disk create --size=5M --docker=./Dockerfile sgx-lkl-rootfs.img
Using detected host DNS server in /etc/resolv.conf: 168.63.129.16
Creating sgx-lkl-rootfs.img from Dockerfile ./Dockerfile...
Building Docker image...
Creating disk image file from Docker container...
Succesfully created sgx-lkl-rootfs.img.
SGXLKL_VERBOSE=1 SGXLKL_KERNEL_VERBOSE=1 /opt/sgx-lkl-debug/bin/sgx-lkl-run-oe --hw-debug sgx-lkl-rootfs.img helloworld
[   SGX-LKL  ] SGX-LKL (OE) 0.2.0-dev (bc148c0) LKL 5.3.0 [DEBUG build (-O0)] [HARDWARE DEBUG]
[   SGX-LKL  ] nproc=4 ETHREADS=8 CMDLINE="mem=32M"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='sgx-lkl-rootfs.img', mnt='/', [RW    ])
[   SGX-LKL  ] No tap device specified, networking will not be available.
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... result=0 (OE_OK)
[   SGX-LKL  ] sgxlkl_enclave_init(ethread_id=0)
[[  SGX-LKL ]] sgxlkl_enclave_init(): enter
[[  SGX-LKL ]] sgxlkl_enclave_show_attribute(): enclave base=0x7fbd80000000 size=2.000 GB
[[  SGX-LKL ]] sgxlkl_enclave_show_attribute(): enclave heap base=0x7fbd80b55000 size=1024.00 M end=0x7fbdc0b55000
[[  SGX-LKL ]] sgxlkl_enclave_init(): calling _dlstart_c()
[[  SGX-LKL ]] _register_enclave_signal_handlers(): Registering OE exception handler...
[[  SGX-LKL ]] lkl_start_init(): kernel command line: 'mem=32M console=hvc0'
[[  SGX-LKL ]] lkl_start_init(): lkl_start_kernel() called
[    0.000000] Linux version 5.3.0+ (AzDevOps@cisca24ba0001LK) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #1 Sun Jun 28 03:04:33 UTC 2020
[    0.000000] memblock address range: 0x7fbdbe8d4000 - 0x7fbdc08d4000
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 8080
[    0.000000] Kernel command line: mem=32M console=hvc0 virtio_mmio.device=256@0x1000000:1
[    0.000000] Dentry cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.000000] Inode-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory available: 32176k/32768k RAM
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 4096
[    0.000000] lkl: irqs initialized
[    0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] lkl: time and timers initialized (irq2)
[    0.000503] printk: console [hvc0] enabled
[    0.000503] pid_max: default: 4096 minimum: 301
[    0.000503] Mount-cache hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.000503] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.002580] devtmpfs: initialized
[    0.006416] random: get_random_bytes called from 0x00007fbd8066ef6a with crng_init=0
[    0.006416] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.006416] futex hash table entries: 16 (order: -4, 384 bytes, linear)
[    0.006416] xor: automatically using best checksumming function   8regs     
[    0.006970] NET: Registered protocol family 16
[    0.010242] clocksource: Switched to clocksource lkl
[    0.010799] NET: Registered protocol family 2
[    0.011353] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.011353] TCP established hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.011353] TCP bind hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.011353] TCP: Hash tables configured (established 512 bind 512)
[    0.011353] UDP hash table entries: 128 (order: 0, 4096 bytes, linear)
[    0.011353] UDP-Lite hash table entries: 128 (order: 0, 4096 bytes, linear)
[    0.011353] NET: Registered protocol family 1
[    0.011353] virtio-mmio: Registering device virtio-mmio.0 at 0x1000000-0x10000ff, IRQ 1.
[    0.011909] workingset: timestamp_bits=62 max_order=14 bucket_order=0
[    0.012464] NET: Registered protocol family 38
[    0.012464] io scheduler mq-deadline registered
[    0.012464] io scheduler kyber registered
[    0.090329] software IO TLB: mapped [mem 0x7fbe76999000-0x7fbe7a999000] (64MB)
[    0.092549] loop: module loaded
[    0.092549] device-mapper: ioctl: 4.40.0-ioctl (2019-01-18) initialised: dm-devel@redhat.com
[    0.093106] wireguard: WireGuard 0.0.20191219 loaded. See www.wireguard.com for information.
[    0.093663] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[    0.093663] NET: Registered protocol family 10
[    0.096345] Segment Routing with IPv6
[    0.096345] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.104614] This architecture does not have kernel memory protection.
[    0.104614] Run /init as init process
[[  SGX-LKL ]] lkl_start_init(): lkl_start_kernel() finished
[[  SGX-LKL ]] lkl_start_init(): creating LKL termination thread
[[  SGX-LKL ]] create_lkl_termination_thread(): enter
[[  SGX-LKL ]] lkl_start_init(): calling lkl_mount_virtial()
[[  SGX-LKL ]] lkl_termination_thread(): enter
[[  SGX-LKL ]] lkl_termination_thread(): Performed LKL syscall to get host task allocated (pid=36)
[[  SGX-LKL ]] lkl_start_init(): calling init_random()
[[  SGX-LKL ]] init_random(): Adding entropy to entropy pool
[    0.105728] random: crng init done
[[  SGX-LKL ]] init_enclave_clock(): Setting enclave realtime clock
[[  SGX-LKL ]] wg0 has public key b5JXGnyXeoxWCHR31F+bxqcSfx3x0e/64gTpSX+B0iw=
[    0.107399] virtio_blk virtio1: [vda] 10240 512-byte logical blocks (5.24 MB/5.00 MiB)
[[  SGX-LKL ]] lkl_mount_disk(): lkl_mount_disk(dev="/dev/vda", mnt="/mnt/vda", ro=0)
[    0.113444] EXT4-fs (vda): mounted filesystem without journal. Opts: 
[[  SGX-LKL ]] lkl_mount_disks(): Set working directory: /
[[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: helloworld
Hello SGX-LKL-OE World!
[[  SGX-LKL ]] lkl_terminate(): terminating LKL (exit_status=0)
[[  SGX-LKL ]] lkl_termination_thread(): termination thread unblocked
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_sys_chdir(/)
[[  SGX-LKL ]] display_mount_table(): ========= /proc/mounts ===========
/dev/vda / ext4 rw,relatime 0 0
devtmpfs /dev devtmpfs rw,relatime 0 0
tmpfs /dev/shm tmpfs rw,relatime 0 0
tmpfs /tmp tmpfs rw,relatime,mode=777 0 0
tmpfs /mnt tmpfs rw,relatime,mode=777 0 0
none /sys sysfs rw,relatime 0 0
tmpfs /run tmpfs rw,relatime,mode=700 0 0
proc /proc proc rw,relatime 0 0
[[  SGX-LKL ]] display_mount_table(): ==================================
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_umount_timeout("/", MNT_DETACH, 2000)
[[  SGX-LKL ]] display_mount_table(): /proc/mounts cannot be accessed
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_virtio_netdev_remove()
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_sys_halt()
[    0.119252] reboot: Restarting system
[[  SGX-LKL ]] lkl_termination_thread(): lthread_detach2() done
[   SGX-LKL  ] ethread (4: 0) ethread (5: 0) ethread (6: 0) 2020-06-28T03:38:37.000000Z [(H)ERROR] tid(0x7fbe727d2700) | :OE_ENCLAVE_ABORTING [/agent/_work/1/s/openenclave/host/calls.c:oe_call_enclave_function_by_table_id:91]
ethread (3: 19) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (id=3 result=19 (OE_ENCLAVE_ABORTING))
ethread (7: 0) Makefile:29: recipe for target 'run-hw' failed
make: *** [run-hw] Error 1
make run-hw: FAILED WITH EXIT CODE: 2
Test run completed with EXIT CODE 2
```

The following code is executed before the init ethread leaves the enclave:
```
    /* Free the shutdown semaphore late in the shutdown sequence */
    sgxlkl_host_ops.sem_free(termination_sem);

    sgxlkl_free_config(sgxlkl_enclave);

    lthread_exit(NULL);
```

We need to figure out what could be causing the enclave abort. How can we output details why OE is aborting the enclave?

(cc: @mikbras @jhand2)

### PR DESCRIPTION
**Pull request by prp**
This PR tries to fix https://github.com/lsds/sgx-lkl/issues/560:

- It reports unhandled exceptions during LKL shutdown, which otherwise may be ignored silently.

- It also removes access to deallocated lthread state.

### CODE REVIEW

File: src/enclave/enclave_signal.c [hunk 1]
```diff
@@ -151,10 +152,11 @@ static uint64_t sgxlkl_enclave_signal_handler(
...
-         * exception and fail instead.
+         * If LKL has not yet been initialised or is terminating (and thus no
+         * longer accepts signals), we cannot handle the exception and fail
+         * instead.
          */
-        if (!lkl_is_running())
+        if (!lkl_is_running() || is_lkl_terminating())
         {
 #ifdef DEBUG
             sgxlkl_error("Exception received before LKL can handle it. "
```
Comment (SeanTAllen) [inline src/enclave/enclave_signal.c]: This message is misleading now as it could either before or after LKL can handle it.

File: src/enclave/enclave_signal.c [hunk 2]
```diff
@@ -151,10 +152,11 @@ static uint64_t sgxlkl_enclave_signal_handler(
...
 
         /**
-         * If LKL has not yet been initialised, we cannot handle the
-         * exception and fail instead.
+         * If LKL has not yet been initialised or is terminating (and thus no
+         * longer accepts signals), we cannot handle the exception and fail
+         * instead.
          */
-        if (!lkl_is_running())
+        if (!lkl_is_running() || is_lkl_terminating())
```
Comment (SeanTAllen) [inline src/enclave/enclave_signal.c:159]: small thing.

there appears to only be two usages of lkl_is_running.

both are !lkl_is_running ie testing the negation.

Given this change, I think it would read easier if it was changed to

lkl_isnt_running()

File: src/enclave/enclave_signal.c (hunk 1 above)
Comment (prp) [reply src/enclave/enclave_signal.c]: Good point. Fixed.

File: src/enclave/enclave_signal.c (hunk 2 above)
Comment (prp) [reply src/enclave/enclave_signal.c:159]: Hmm, since that function may change with the re-layering anyway, I don't think it's worth changing it now.

File: src/sched/lthread.c [hunk 3]
```diff
@@ -263,7 +262,8 @@ void lthread_run(void)
         /* Break out of scheduler loop when enclave is terminating */
         if (_lthread_should_stop)
         {
-            SGXLKL_TRACE_THREAD("[tid=%-3d] lthread_run() quiting.\n", lt->tid);
+            SGXLKL_TRACE_THREAD(
+                "[tid=%-3d] lthread_run(): quiting\n", lt ? lt->tid : -1);
```
Comment (letmaik) [inline src/sched/lthread.c]:
```suggestion
                "[tid=%-3d] lthread_run(): quitting\n", lt ? lt->tid : -1);
```

**Review by letmaik — APPROVED** [review]

File: src/sched/lthread.c (hunk 3 above)
Comment (prp) [reply src/sched/lthread.c]: Done
