### PR TITLE
Return error code when dev_register() fails

### LINKED ISSUE #370: lkl_virtio_netdev_add ignores errors
- Return code of `lkl_virtio_dev_setup()` is not checked.
- Return code of `dev_register()` is checked but only leads to `sgxlkl_info(..)` on error.

### PR DESCRIPTION
**Pull request by AntonioND**
Instead of just printing an error message, return an error code so that
the caller of lkl_virtio_netdev_add() knows that it has failed.

Along with PR #753, this fixes #370.

### CODE REVIEW

**Review by prp — APPROVED** [review]
LGTM.

File: src/lkl/virtio_netdev.c [hunk 1]
```diff
@@ -72,9 +72,11 @@ int lkl_virtio_netdev_add(struct virtio_dev* netdev)
         return -1;
 
     ret = dev_register(netdev);
-
     if (ret < 0)
-        sgxlkl_info("Failed to register netdev \n");
+    {
+        sgxlkl_info("Failed to register netdev\n");
```
Comment (davidchisnall) [inline src/lkl/virtio_netdev.c]: I think this should just be `sgxlkl_fail`.  What does the caller do with the `-1` return value?

Comment (AntonioND) [reply src/lkl/virtio_netdev.c]: It's used in ``src/lkl/setup.c:1401``:

```
// Register network tap if given one
int net_dev_id = -1;
if (shm->virtio_net_dev_mem)
    net_dev_id = lkl_virtio_netdev_add(shm->virtio_net_dev_mem);
```

It looks like returning -1 is just interpreted as "no network tap present".

Comment (AntonioND) [reply src/lkl/virtio_netdev.c]: Also, I've changed the info to fail as you suggested.

Comment (davidchisnall) [reply src/lkl/virtio_netdev.c]: I don't want to have to reason about the security implications of the network device being not present.  Simply failing is easy to reason about.

**Review by davidchisnall — APPROVED** [review]

File: src/lkl/virtio_netdev.c (hunk 1 above)
Comment (AntonioND) [reply src/lkl/virtio_netdev.c]: Wait, I'm confused, do you mean that the changes are good as they are, or that I need a stronger way to fail?

Comment (SeanTAllen) [reply src/lkl/virtio_netdev.c]: He was explaining why he wanted to fail instead of having the error bubble up.

Comment (davidchisnall) [reply src/lkl/virtio_netdev.c]: Confusing conversation history caused by a race condition: I wrote that before your second command and the push of the change that turned it to a fail.

**Comment by davidchisnall** [comment]
The CI failure looks unrelated.

**Comment by prp** [comment]
Didn't @KenGordon recently reactivate the failing test? The test actually seems to have passed but it still returns an error code...?

**Review by vtikoo — APPROVED** [review]
LGTM
